// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

public import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Authority encodes how Google will recognize identities from this Membership.
/// See the workload identity documentation for more details:
/// https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity
public struct Authority: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. A JSON Web Token (JWT) issuer URI. `issuer` must start with
  /// `https://` and be a valid URL with length <2000 characters.
  ///
  /// If set, then Google will allow valid OIDC tokens from this issuer to
  /// authenticate within the workload_identity_pool. OIDC discovery will be
  /// performed on this URI to validate tokens from the issuer.
  ///
  /// Clearing `issuer` disables Workload Identity. `issuer` cannot be directly
  /// modified; it must be cleared (and Workload Identity disabled) before using
  /// a new issuer (and re-enabling Workload Identity).
  public var issuer: Swift.String = Swift.String()

  /// Output only. The name of the workload identity pool in which `issuer` will
  /// be recognized.
  ///
  /// There is a single Workload Identity Pool per Hub that is shared
  /// between all Memberships that belong to that Hub. For a Hub hosted in
  /// {PROJECT_ID}, the workload pool format is `{PROJECT_ID}.hub.id.goog`,
  /// although this is subject to change in newer versions of this API.
  public var workloadIdentityPool: Swift.String = Swift.String()

  /// Output only. An identity provider that reflects the `issuer` in the
  /// workload identity pool.
  public var identityProvider: Swift.String = Swift.String()

  /// Optional. OIDC verification keys for this Membership in JWKS format (RFC
  /// 7517).
  ///
  /// When this field is set, OIDC discovery will NOT be performed on `issuer`,
  /// and instead OIDC tokens will be validated using this field.
  public var oidcJwks: Foundation.Data = Foundation.Data()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Authority`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Authority().with { $0.issuer = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let issuer = CodingKeys(stringValue: "issuer")
    static let workloadIdentityPool = CodingKeys(stringValue: "workloadIdentityPool")
    static let identityProvider = CodingKeys(stringValue: "identityProvider")
    static let oidcJwks = CodingKeys(stringValue: "oidcJwks")

    static let _knownKeys: Set<Swift.String> = [
      "issuer",
      "workloadIdentityPool",
      "identityProvider",
      "oidcJwks",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .issuer) {
      self.issuer = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .workloadIdentityPool) {
      self.workloadIdentityPool = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .identityProvider) {
      self.identityProvider = value
    }
    if let value = try container.decodeIfPresent(Foundation.Data.self, forKey: .oidcJwks) {
      self.oidcJwks = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.issuer, forKey: .issuer)
    try container.encode(self.workloadIdentityPool, forKey: .workloadIdentityPool)
    try container.encode(self.identityProvider, forKey: .identityProvider)
    try container.encode(self.oidcJwks, forKey: .oidcJwks)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `Authority`: `"type.googleapis.com/google.cloud.gkehub.v1.Authority"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkehub.v1.Authority"
  }

  /// Initialize an instance of `Authority` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.gkehub.v1.Authority"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `Authority` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
