// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleCloudGKEHubRBACRoleBindingActuationV1
@_spi(GoogleCloudInternal) public import GoogleWKT

/// CommonFeatureState contains Fleet-wide Feature status information.
public struct CommonFeatureState: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The "running state" of the Feature in this Fleet.
  public var state: GoogleCloudGKEHubV1.FeatureState? = nil

  public var featureState: FeatureStateOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CommonFeatureState`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CommonFeatureState().with { $0.rbacrolebindingactuation = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let rbacrolebindingactuation = CodingKeys(stringValue: "rbacrolebindingactuation")
    static let state = CodingKeys(stringValue: "state")

    static let _knownKeys: Set<Swift.String> = [
      "rbacrolebindingactuation",
      "state",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.state = try container.decodeIfPresent(
      GoogleCloudGKEHubV1.FeatureState.self, forKey: .state)

    var featureState: FeatureStateOneOf? = nil
    let featureStateCheckAndSet = {
      if featureState != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'featureState'"))
      }
      featureState = $0
    }
    if let rbacrolebindingactuation = try container.decodeIfPresent(
      GoogleCloudGKEHubRBACRoleBindingActuationV1.FeatureState.self,
      forKey: .rbacrolebindingactuation)
    {
      try featureStateCheckAndSet(.rbacrolebindingactuation(rbacrolebindingactuation))
    }
    self.featureState = featureState
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.state, forKey: .state)

    if let choice = self.featureState {
      switch choice {
      case .rbacrolebindingactuation(let value):
        try container.encode(value, forKey: .rbacrolebindingactuation)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public enum FeatureStateOneOf: Codable, Equatable, Sendable {
    /// RBAC Role Binding Actuation feature state
    indirect case rbacrolebindingactuation(GoogleCloudGKEHubRBACRoleBindingActuationV1.FeatureState)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkehub.v1.CommonFeatureState"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
