// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request to create a rbacrolebindings.
public struct CreateMembershipRBACRoleBindingRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The parent (project and location) where the RBACRoleBinding will
  /// be created. Specified in the format `projects/*/locations/*/memberships/*`.
  public var parent: Swift.String = Swift.String()

  /// Required. Client chosen ID for the RBACRoleBinding. `rbacrolebinding_id`
  /// must be a valid RFC 1123 compliant DNS label:
  ///
  ///   1. At most 63 characters in length
  ///   2. It must consist of lower case alphanumeric characters or `-`
  ///   3. It must start and end with an alphanumeric character
  ///
  /// Which can be expressed as the regex: `[a-z0-9]([-a-z0-9]*[a-z0-9])?`,
  /// with a maximum length of 63 characters.
  public var rbacrolebindingId: Swift.String = Swift.String()

  /// Required. The rbacrolebindings to create.
  public var rbacrolebinding: RBACRoleBinding? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CreateMembershipRBACRoleBindingRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateMembershipRBACRoleBindingRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let rbacrolebindingId = CodingKeys(stringValue: "rbacrolebindingId")
    static let rbacrolebinding = CodingKeys(stringValue: "rbacrolebinding")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "rbacrolebindingId",
      "rbacrolebinding",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .rbacrolebindingId) {
      self.rbacrolebindingId = value
    }
    self.rbacrolebinding = try container.decodeIfPresent(
      RBACRoleBinding.self, forKey: .rbacrolebinding)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.rbacrolebindingId, forKey: .rbacrolebindingId)
    try container.encodeIfPresent(self.rbacrolebinding, forKey: .rbacrolebinding)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkehub.v1.CreateMembershipRBACRoleBindingRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
