// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request to create a fleet namespace.
public struct CreateScopeNamespaceRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The parent (project and location) where the Namespace will be
  /// created. Specified in the format `projects/*/locations/*/scopes/*`.
  public var parent: Swift.String = Swift.String()

  /// Required. Client chosen ID for the Namespace. `namespace_id` must be a
  /// valid RFC 1123 compliant DNS label:
  ///
  ///   1. At most 63 characters in length
  ///   2. It must consist of lower case alphanumeric characters or `-`
  ///   3. It must start and end with an alphanumeric character
  ///
  /// Which can be expressed as the regex: `[a-z0-9]([-a-z0-9]*[a-z0-9])?`,
  /// with a maximum length of 63 characters.
  public var scopeNamespaceId: Swift.String = Swift.String()

  /// Required. The fleet namespace to create.
  public var scopeNamespace: Namespace? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CreateScopeNamespaceRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateScopeNamespaceRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let scopeNamespaceId = CodingKeys(stringValue: "scopeNamespaceId")
    static let scopeNamespace = CodingKeys(stringValue: "scopeNamespace")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "scopeNamespaceId",
      "scopeNamespace",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .scopeNamespaceId) {
      self.scopeNamespaceId = value
    }
    self.scopeNamespace = try container.decodeIfPresent(Namespace.self, forKey: .scopeNamespace)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.scopeNamespaceId, forKey: .scopeNamespaceId)
    try container.encodeIfPresent(self.scopeNamespace, forKey: .scopeNamespace)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `CreateScopeNamespaceRequest`: `"type.googleapis.com/google.cloud.gkehub.v1.CreateScopeNamespaceRequest"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkehub.v1.CreateScopeNamespaceRequest"
  }

  /// Initialize an instance of `CreateScopeNamespaceRequest` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.gkehub.v1.CreateScopeNamespaceRequest"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `CreateScopeNamespaceRequest` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
