// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// DefaultClusterConfig describes the default cluster configurations to be
/// applied to all clusters born-in-fleet.
public struct DefaultClusterConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Enable/Disable Security Posture features for the cluster.
  public var securityPostureConfig: SecurityPostureConfig? = nil

  /// Optional. Enable/Disable binary authorization features for the cluster.
  public var binaryAuthorizationConfig: BinaryAuthorizationConfig? = nil

  /// Optional. Enable/Disable Compliance Posture features for the cluster.
  /// Note that on UpdateFleet, only full replacement of this field is allowed.
  /// Users are not allowed for partial updates through field mask.
  public var compliancePostureConfig: CompliancePostureConfig? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DefaultClusterConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DefaultClusterConfig().with { $0.securityPostureConfig = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let securityPostureConfig = CodingKeys(stringValue: "securityPostureConfig")
    static let binaryAuthorizationConfig = CodingKeys(stringValue: "binaryAuthorizationConfig")
    static let compliancePostureConfig = CodingKeys(stringValue: "compliancePostureConfig")

    static let _knownKeys: Set<Swift.String> = [
      "securityPostureConfig",
      "binaryAuthorizationConfig",
      "compliancePostureConfig",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.securityPostureConfig = try container.decodeIfPresent(
      SecurityPostureConfig.self, forKey: .securityPostureConfig)
    self.binaryAuthorizationConfig = try container.decodeIfPresent(
      BinaryAuthorizationConfig.self, forKey: .binaryAuthorizationConfig)
    self.compliancePostureConfig = try container.decodeIfPresent(
      CompliancePostureConfig.self, forKey: .compliancePostureConfig)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.securityPostureConfig, forKey: .securityPostureConfig)
    try container.encodeIfPresent(
      self.binaryAuthorizationConfig, forKey: .binaryAuthorizationConfig)
    try container.encodeIfPresent(self.compliancePostureConfig, forKey: .compliancePostureConfig)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkehub.v1.DefaultClusterConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
