// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Feature represents the settings and status of any Fleet Feature.
public struct Feature: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The full, unique name of this Feature resource in the format
  /// `projects/*/locations/*/features/*`.
  public var name: Swift.String = Swift.String()

  /// Labels for this Feature.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. State of the Feature resource itself.
  public var resourceState: FeatureResourceState? = nil

  /// Optional. Fleet-wide Feature configuration. If this Feature does not
  /// support any Fleet-wide configuration, this field may be unused.
  public var spec: CommonFeatureSpec? = nil

  /// Optional. Membership-specific configuration for this Feature. If this
  /// Feature does not support any per-Membership configuration, this field may
  /// be unused.
  ///
  /// The keys indicate which Membership the configuration is for, in the form:
  ///
  /// `projects/{p}/locations/{l}/memberships/{m}`
  ///
  /// Where {p} is the project, {l} is a valid location and {m} is a valid
  /// Membership in this project at that location. {p} WILL match the Feature's
  /// project.
  ///
  /// {p} will always be returned as the project number, but the project ID is
  /// also accepted during input. If the same Membership is specified in the map
  /// twice (using the project ID form, and the project number form), exactly
  /// ONE of the entries will be saved, with no guarantees as to which. For this
  /// reason, it is recommended the same format be used for all entries when
  /// mutating a Feature.
  public var membershipSpecs: [Swift.String: MembershipFeatureSpec] = [:]

  /// Output only. The Fleet-wide Feature state.
  public var state: CommonFeatureState? = nil

  /// Output only. Membership-specific Feature status. If this Feature does
  /// report any per-Membership status, this field may be unused.
  ///
  /// The keys indicate which Membership the state is for, in the form:
  ///
  /// `projects/{p}/locations/{l}/memberships/{m}`
  ///
  /// Where {p} is the project number, {l} is a valid location and {m} is a valid
  /// Membership in this project at that location. {p} MUST match the Feature's
  /// project number.
  public var membershipStates: [Swift.String: MembershipFeatureState] = [:]

  /// Output only. When the Feature resource was created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. When the Feature resource was last updated.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. When the Feature resource was deleted.
  public var deleteTime: GoogleWKT.WKTTimestamp? = nil

  /// Optional. Scope-specific configuration for this Feature. If this Feature
  /// does not support any per-Scope configuration, this field may be unused.
  ///
  /// The keys indicate which Scope the configuration is for, in the form:
  ///
  /// `projects/{p}/locations/global/scopes/{s}`
  ///
  /// Where {p} is the project, {s} is a valid Scope in this project.
  /// {p} WILL match the Feature's project.
  ///
  /// {p} will always be returned as the project number, but the project ID is
  /// also accepted during input. If the same Scope is specified in the map
  /// twice (using the project ID form, and the project number form), exactly
  /// ONE of the entries will be saved, with no guarantees as to which. For this
  /// reason, it is recommended the same format be used for all entries when
  /// mutating a Feature.
  public var scopeSpecs: [Swift.String: ScopeFeatureSpec] = [:]

  /// Output only. Scope-specific Feature status. If this Feature does
  /// report any per-Scope status, this field may be unused.
  ///
  /// The keys indicate which Scope the state is for, in the form:
  ///
  /// `projects/{p}/locations/global/scopes/{s}`
  ///
  /// Where {p} is the project, {s} is a valid Scope in this project.
  /// {p} WILL match the Feature's project.
  public var scopeStates: [Swift.String: ScopeFeatureState] = [:]

  /// Output only. List of locations that could not be reached while fetching
  /// this feature.
  public var unreachable: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Feature`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Feature().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let labels = CodingKeys(stringValue: "labels")
    static let resourceState = CodingKeys(stringValue: "resourceState")
    static let spec = CodingKeys(stringValue: "spec")
    static let membershipSpecs = CodingKeys(stringValue: "membershipSpecs")
    static let state = CodingKeys(stringValue: "state")
    static let membershipStates = CodingKeys(stringValue: "membershipStates")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let deleteTime = CodingKeys(stringValue: "deleteTime")
    static let scopeSpecs = CodingKeys(stringValue: "scopeSpecs")
    static let scopeStates = CodingKeys(stringValue: "scopeStates")
    static let unreachable = CodingKeys(stringValue: "unreachable")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "labels",
      "resourceState",
      "spec",
      "membershipSpecs",
      "state",
      "membershipStates",
      "createTime",
      "updateTime",
      "deleteTime",
      "scopeSpecs",
      "scopeStates",
      "unreachable",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    self.resourceState = try container.decodeIfPresent(
      FeatureResourceState.self, forKey: .resourceState)
    self.spec = try container.decodeIfPresent(CommonFeatureSpec.self, forKey: .spec)
    if let value = try container.decodeIfPresent(
      [Swift.String: MembershipFeatureSpec].self, forKey: .membershipSpecs)
    {
      self.membershipSpecs = value
    }
    self.state = try container.decodeIfPresent(CommonFeatureState.self, forKey: .state)
    if let value = try container.decodeIfPresent(
      [Swift.String: MembershipFeatureState].self, forKey: .membershipStates)
    {
      self.membershipStates = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    self.deleteTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .deleteTime)
    if let value = try container.decodeIfPresent(
      [Swift.String: ScopeFeatureSpec].self, forKey: .scopeSpecs)
    {
      self.scopeSpecs = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: ScopeFeatureState].self, forKey: .scopeStates)
    {
      self.scopeStates = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .unreachable) {
      self.unreachable = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.labels, forKey: .labels)
    try container.encodeIfPresent(self.resourceState, forKey: .resourceState)
    try container.encodeIfPresent(self.spec, forKey: .spec)
    try container.encode(self.membershipSpecs, forKey: .membershipSpecs)
    try container.encodeIfPresent(self.state, forKey: .state)
    try container.encode(self.membershipStates, forKey: .membershipStates)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encodeIfPresent(self.deleteTime, forKey: .deleteTime)
    try container.encode(self.scopeSpecs, forKey: .scopeSpecs)
    try container.encode(self.scopeStates, forKey: .scopeStates)
    try container.encode(self.unreachable, forKey: .unreachable)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkehub.v1.Feature"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
