// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Fleet contains the Fleet-wide metadata and configuration.
public struct Fleet: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The full, unique resource name of this fleet in the format of
  /// `projects/{project}/locations/{location}/fleets/{fleet}`.
  ///
  /// Each Google Cloud project can have at most one fleet resource, named
  /// "default".
  public var name: Swift.String = Swift.String()

  /// Optional. A user-assigned display name of the Fleet.
  /// When present, it must be between 4 to 30 characters.
  /// Allowed characters are: lowercase and uppercase letters, numbers,
  /// hyphen, single-quote, double-quote, space, and exclamation point.
  ///
  /// Example: `Production Fleet`
  public var displayName: Swift.String = Swift.String()

  /// Output only. When the Fleet was created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. When the Fleet was last updated.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. When the Fleet was deleted.
  public var deleteTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Google-generated UUID for this resource. This is unique across
  /// all Fleet resources. If a Fleet resource is deleted and another resource
  /// with the same name is created, it gets a different uid.
  public var uid: Swift.String = Swift.String()

  /// Output only. State of the namespace resource.
  public var state: FleetLifecycleState? = nil

  /// Optional. The default cluster configurations to apply across the fleet.
  public var defaultClusterConfig: DefaultClusterConfig? = nil

  /// Optional. Labels for this Fleet.
  public var labels: [Swift.String: Swift.String] = [:]

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Fleet`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Fleet().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let deleteTime = CodingKeys(stringValue: "deleteTime")
    static let uid = CodingKeys(stringValue: "uid")
    static let state = CodingKeys(stringValue: "state")
    static let defaultClusterConfig = CodingKeys(stringValue: "defaultClusterConfig")
    static let labels = CodingKeys(stringValue: "labels")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "displayName",
      "createTime",
      "updateTime",
      "deleteTime",
      "uid",
      "state",
      "defaultClusterConfig",
      "labels",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    self.deleteTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .deleteTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uid) {
      self.uid = value
    }
    self.state = try container.decodeIfPresent(FleetLifecycleState.self, forKey: .state)
    self.defaultClusterConfig = try container.decodeIfPresent(
      DefaultClusterConfig.self, forKey: .defaultClusterConfig)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encodeIfPresent(self.deleteTime, forKey: .deleteTime)
    try container.encode(self.uid, forKey: .uid)
    try container.encodeIfPresent(self.state, forKey: .state)
    try container.encodeIfPresent(self.defaultClusterConfig, forKey: .defaultClusterConfig)
    try container.encode(self.labels, forKey: .labels)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `Fleet`: `"type.googleapis.com/google.cloud.gkehub.v1.Fleet"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkehub.v1.Fleet"
  }

  /// Initialize an instance of `Fleet` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.gkehub.v1.Fleet"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `Fleet` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
