// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// KubernetesMetadata provides informational metadata for Memberships
/// representing Kubernetes clusters.
public struct KubernetesMetadata: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. Kubernetes API server version string as reported by
  /// `/version`.
  public var kubernetesApiServerVersion: Swift.String = Swift.String()

  /// Output only. Node providerID as reported by the first node in the list of
  /// nodes on the Kubernetes endpoint. On Kubernetes platforms that support
  /// zero-node clusters (like GKE-on-GCP), the node_count will be zero and the
  /// node_provider_id will be empty.
  public var nodeProviderId: Swift.String = Swift.String()

  /// Output only. Node count as reported by Kubernetes nodes resources.
  public var nodeCount: Swift.Int32 = Swift.Int32()

  /// Output only. vCPU count as reported by Kubernetes nodes resources.
  public var vcpuCount: Swift.Int32 = Swift.Int32()

  /// Output only. The total memory capacity as reported by the sum of all
  /// Kubernetes nodes resources, defined in MB.
  public var memoryMb: Swift.Int32 = Swift.Int32()

  /// Output only. The time at which these details were last updated. This
  /// update_time is different from the Membership-level update_time since
  /// EndpointDetails are updated internally for API consumers.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `KubernetesMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = KubernetesMetadata().with { $0.kubernetesApiServerVersion = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let kubernetesApiServerVersion = CodingKeys(stringValue: "kubernetesApiServerVersion")
    static let nodeProviderId = CodingKeys(stringValue: "nodeProviderId")
    static let nodeCount = CodingKeys(stringValue: "nodeCount")
    static let vcpuCount = CodingKeys(stringValue: "vcpuCount")
    static let memoryMb = CodingKeys(stringValue: "memoryMb")
    static let updateTime = CodingKeys(stringValue: "updateTime")

    static let _knownKeys: Set<Swift.String> = [
      "kubernetesApiServerVersion",
      "nodeProviderId",
      "nodeCount",
      "vcpuCount",
      "memoryMb",
      "updateTime",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .kubernetesApiServerVersion)
    {
      self.kubernetesApiServerVersion = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .nodeProviderId) {
      self.nodeProviderId = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .nodeCount) {
      self.nodeCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .vcpuCount) {
      self.vcpuCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .memoryMb) {
      self.memoryMb = value
    }
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.kubernetesApiServerVersion, forKey: .kubernetesApiServerVersion)
    try container.encode(self.nodeProviderId, forKey: .nodeProviderId)
    try container.encode(self.nodeCount, forKey: .nodeCount)
    try container.encode(self.vcpuCount, forKey: .vcpuCount)
    try container.encode(self.memoryMb, forKey: .memoryMb)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkehub.v1.KubernetesMetadata"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
