// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleGax
@_spi(GoogleCloudInternal) public import GoogleWKT

/// List of Membership RBACRoleBindings.
public struct ListMembershipRBACRoleBindingsResponse: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The list of Membership RBACRoleBindings.
  public var rbacrolebindings: [RBACRoleBinding] = []

  /// A token to request the next page of resources from the
  /// `ListMembershipRBACRoleBindings` method. The value of an empty string means
  /// that there are no more resources to return.
  public var nextPageToken: Swift.String = Swift.String()

  /// List of locations that could not be reached while fetching this list.
  public var unreachable: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ListMembershipRBACRoleBindingsResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListMembershipRBACRoleBindingsResponse().with { $0.rbacrolebindings = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let rbacrolebindings = CodingKeys(stringValue: "rbacrolebindings")
    static let nextPageToken = CodingKeys(stringValue: "nextPageToken")
    static let unreachable = CodingKeys(stringValue: "unreachable")

    static let _knownKeys: Set<Swift.String> = [
      "rbacrolebindings",
      "nextPageToken",
      "unreachable",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent([RBACRoleBinding].self, forKey: .rbacrolebindings)
    {
      self.rbacrolebindings = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .nextPageToken) {
      self.nextPageToken = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .unreachable) {
      self.unreachable = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.rbacrolebindings, forKey: .rbacrolebindings)
    try container.encode(self.nextPageToken, forKey: .nextPageToken)
    try container.encode(self.unreachable, forKey: .unreachable)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `ListMembershipRBACRoleBindingsResponse`: `"type.googleapis.com/google.cloud.gkehub.v1.ListMembershipRBACRoleBindingsResponse"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkehub.v1.ListMembershipRBACRoleBindingsResponse"
  }

  /// Initialize an instance of `ListMembershipRBACRoleBindingsResponse` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.gkehub.v1.ListMembershipRBACRoleBindingsResponse"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `ListMembershipRBACRoleBindingsResponse` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}

@_spi(GoogleCloudInternal)
extension ListMembershipRBACRoleBindingsResponse: GoogleGax._PaginatedResponse {
  public func _getPaginatedItems() -> [RBACRoleBinding] {
    return self.rbacrolebindings
  }

  public func _nextPageToken() -> Swift.String {
    return self.nextPageToken
  }
}
