// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// MembershipEndpoint contains information needed to contact a Kubernetes API,
/// endpoint and any additional Kubernetes metadata.
public struct MembershipEndpoint: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. GKE-specific information. Only present if this Membership is a GKE cluster.
  public var gkeCluster: GkeCluster? = nil

  /// Output only. Useful Kubernetes-specific metadata.
  public var kubernetesMetadata: KubernetesMetadata? = nil

  /// Optional. The in-cluster Kubernetes Resources that should be applied for a
  /// correctly registered cluster, in the steady state. These resources:
  ///
  ///   * Ensure that the cluster is exclusively registered to one and only one
  ///     Hub Membership.
  ///   * Propagate Workload Pool Information available in the Membership
  ///     Authority field.
  ///   * Ensure proper initial configuration of default Hub Features.
  public var kubernetesResource: KubernetesResource? = nil

  /// Output only. Whether the lifecycle of this membership is managed by a
  /// google cluster platform service.
  public var googleManaged: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `MembershipEndpoint`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MembershipEndpoint().with { $0.gkeCluster = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let gkeCluster = CodingKeys(stringValue: "gkeCluster")
    static let kubernetesMetadata = CodingKeys(stringValue: "kubernetesMetadata")
    static let kubernetesResource = CodingKeys(stringValue: "kubernetesResource")
    static let googleManaged = CodingKeys(stringValue: "googleManaged")

    static let _knownKeys: Set<Swift.String> = [
      "gkeCluster",
      "kubernetesMetadata",
      "kubernetesResource",
      "googleManaged",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.gkeCluster = try container.decodeIfPresent(GkeCluster.self, forKey: .gkeCluster)
    self.kubernetesMetadata = try container.decodeIfPresent(
      KubernetesMetadata.self, forKey: .kubernetesMetadata)
    self.kubernetesResource = try container.decodeIfPresent(
      KubernetesResource.self, forKey: .kubernetesResource)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .googleManaged) {
      self.googleManaged = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.gkeCluster, forKey: .gkeCluster)
    try container.encodeIfPresent(self.kubernetesMetadata, forKey: .kubernetesMetadata)
    try container.encodeIfPresent(self.kubernetesResource, forKey: .kubernetesResource)
    try container.encode(self.googleManaged, forKey: .googleManaged)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkehub.v1.MembershipEndpoint"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
