// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleCloudGKEHubConfigManagementV1
@_spi(GoogleCloudInternal) public import GoogleWKT

/// MembershipFeatureSpec contains configuration information for a single
/// Membership.
public struct MembershipFeatureSpec: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  public var featureSpec: FeatureSpecOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `MembershipFeatureSpec`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MembershipFeatureSpec().with { $0.configmanagement = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let configmanagement = CodingKeys(stringValue: "configmanagement")

    static let _knownKeys: Set<Swift.String> = [
      "configmanagement"
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var featureSpec: FeatureSpecOneOf? = nil
    let featureSpecCheckAndSet = {
      if featureSpec != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'featureSpec'"))
      }
      featureSpec = $0
    }
    if let configmanagement = try container.decodeIfPresent(
      GoogleCloudGKEHubConfigManagementV1.MembershipSpec.self, forKey: .configmanagement)
    {
      try featureSpecCheckAndSet(.configmanagement(configmanagement))
    }
    self.featureSpec = featureSpec
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.featureSpec {
      switch choice {
      case .configmanagement(let value):
        try container.encode(value, forKey: .configmanagement)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public enum FeatureSpecOneOf: Codable, Equatable, Sendable {
    /// Config Management-specific spec.
    indirect case configmanagement(GoogleCloudGKEHubConfigManagementV1.MembershipSpec)
  }

  /// The type URL for `MembershipFeatureSpec`: `"type.googleapis.com/google.cloud.gkehub.v1.MembershipFeatureSpec"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkehub.v1.MembershipFeatureSpec"
  }

  /// Initialize an instance of `MembershipFeatureSpec` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.gkehub.v1.MembershipFeatureSpec"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `MembershipFeatureSpec` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
