// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// MembershipBinding is a subresource of a Membership, representing
/// what Fleet Scopes (or other, future Fleet resources) a Membership is bound
/// to.
public struct MembershipBinding: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The resource name for the membershipbinding itself
  /// `projects/{project}/locations/{location}/memberships/{membership}/bindings/{membershipbinding}`
  public var name: Swift.String = Swift.String()

  /// Output only. Google-generated UUID for this resource. This is unique across
  /// all membershipbinding resources. If a membershipbinding resource is deleted
  /// and another resource with the same name is created, it gets a different
  /// uid.
  public var uid: Swift.String = Swift.String()

  /// Output only. When the membership binding was created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. When the membership binding was last updated.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. When the membership binding was deleted.
  public var deleteTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. State of the membership binding resource.
  public var state: MembershipBindingLifecycleState? = nil

  /// Optional. Labels for this MembershipBinding.
  public var labels: [Swift.String: Swift.String] = [:]

  /// What type of membershipbinding this is.
  public var target: TargetOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `MembershipBinding`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MembershipBinding().with { $0.scope = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let scope = CodingKeys(stringValue: "scope")
    static let name = CodingKeys(stringValue: "name")
    static let uid = CodingKeys(stringValue: "uid")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let deleteTime = CodingKeys(stringValue: "deleteTime")
    static let state = CodingKeys(stringValue: "state")
    static let labels = CodingKeys(stringValue: "labels")

    static let _knownKeys: Set<Swift.String> = [
      "scope",
      "name",
      "uid",
      "createTime",
      "updateTime",
      "deleteTime",
      "state",
      "labels",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uid) {
      self.uid = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    self.deleteTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .deleteTime)
    self.state = try container.decodeIfPresent(MembershipBindingLifecycleState.self, forKey: .state)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }

    var target: TargetOneOf? = nil
    let targetCheckAndSet = {
      if target != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'target'"))
      }
      target = $0
    }
    if let scope = try container.decodeIfPresent(Swift.String.self, forKey: .scope) {
      try targetCheckAndSet(.scope(scope))
    }
    self.target = target
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.uid, forKey: .uid)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encodeIfPresent(self.deleteTime, forKey: .deleteTime)
    try container.encodeIfPresent(self.state, forKey: .state)
    try container.encode(self.labels, forKey: .labels)

    if let choice = self.target {
      switch choice {
      case .scope(let value):
        try container.encode(value, forKey: .scope)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// What type of membershipbinding this is.
  public enum TargetOneOf: Codable, Equatable, Sendable {
    /// A Scope resource name in the format
    /// `projects/*/locations/*/scopes/*`.
    case scope(Swift.String)
  }

  /// The type URL for `MembershipBinding`: `"type.googleapis.com/google.cloud.gkehub.v1.MembershipBinding"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkehub.v1.MembershipBinding"
  }

  /// Initialize an instance of `MembershipBinding` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.gkehub.v1.MembershipBinding"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `MembershipBinding` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
