// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Membership contains information about a member cluster.
public struct Membership: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The full, unique name of this Membership resource in the
  /// format `projects/*/locations/*/memberships/{membership_id}`, set during
  /// creation.
  ///
  /// `membership_id` must be a valid RFC 1123 compliant DNS label:
  ///
  ///   1. At most 63 characters in length
  ///   2. It must consist of lower case alphanumeric characters or `-`
  ///   3. It must start and end with an alphanumeric character
  ///
  /// Which can be expressed as the regex: `[a-z0-9]([-a-z0-9]*[a-z0-9])?`,
  /// with a maximum length of 63 characters.
  public var name: Swift.String = Swift.String()

  /// Optional. Labels for this membership.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. Description of this membership, limited to 63 characters.
  /// Must match the regex: `[a-zA-Z0-9][a-zA-Z0-9_\-\.\ ]*`
  ///
  /// This field is present for legacy purposes.
  public var description: Swift.String = Swift.String()

  /// Output only. State of the Membership resource.
  public var state: GoogleCloudGKEHubV1.MembershipState? = nil

  /// Output only. When the Membership was created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. When the Membership was last updated.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. When the Membership was deleted.
  public var deleteTime: GoogleWKT.WKTTimestamp? = nil

  /// Optional. An externally-generated and managed ID for this Membership. This
  /// ID may be modified after creation, but this is not recommended.
  ///
  /// The ID must match the regex: `[a-zA-Z0-9][a-zA-Z0-9_\-\.]*`
  ///
  /// If this Membership represents a Kubernetes cluster, this value should be
  /// set to the UID of the `kube-system` namespace object.
  public var externalId: Swift.String = Swift.String()

  /// Output only. For clusters using Connect, the timestamp of the most recent
  /// connection established with Google Cloud. This time is updated every
  /// several minutes, not continuously. For clusters that do not use GKE
  /// Connect, or that have never connected successfully, this field will be
  /// unset.
  public var lastConnectionTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Google-generated UUID for this resource. This is unique across
  /// all Membership resources. If a Membership resource is deleted and another
  /// resource with the same name is created, it gets a different unique_id.
  public var uniqueId: Swift.String = Swift.String()

  /// Optional. How to identify workloads from this Membership.
  /// See the documentation on Workload Identity for more details:
  /// https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity
  public var authority: Authority? = nil

  /// Optional. The monitoring config information for this membership.
  public var monitoringConfig: MonitoringConfig? = nil

  /// Type of resource represented by this Membership
  public var type: TypeOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Membership`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Membership().with { $0.endpoint = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let endpoint = CodingKeys(stringValue: "endpoint")
    static let name = CodingKeys(stringValue: "name")
    static let labels = CodingKeys(stringValue: "labels")
    static let description = CodingKeys(stringValue: "description")
    static let state = CodingKeys(stringValue: "state")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let deleteTime = CodingKeys(stringValue: "deleteTime")
    static let externalId = CodingKeys(stringValue: "externalId")
    static let lastConnectionTime = CodingKeys(stringValue: "lastConnectionTime")
    static let uniqueId = CodingKeys(stringValue: "uniqueId")
    static let authority = CodingKeys(stringValue: "authority")
    static let monitoringConfig = CodingKeys(stringValue: "monitoringConfig")

    static let _knownKeys: Set<Swift.String> = [
      "endpoint",
      "name",
      "labels",
      "description",
      "state",
      "createTime",
      "updateTime",
      "deleteTime",
      "externalId",
      "lastConnectionTime",
      "uniqueId",
      "authority",
      "monitoringConfig",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    self.state = try container.decodeIfPresent(
      GoogleCloudGKEHubV1.MembershipState.self, forKey: .state)
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    self.deleteTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .deleteTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .externalId) {
      self.externalId = value
    }
    self.lastConnectionTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .lastConnectionTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uniqueId) {
      self.uniqueId = value
    }
    self.authority = try container.decodeIfPresent(Authority.self, forKey: .authority)
    self.monitoringConfig = try container.decodeIfPresent(
      MonitoringConfig.self, forKey: .monitoringConfig)

    var type: TypeOneOf? = nil
    let typeCheckAndSet = {
      if type != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'type'"
          ))
      }
      type = $0
    }
    if let endpoint = try container.decodeIfPresent(MembershipEndpoint.self, forKey: .endpoint) {
      try typeCheckAndSet(.endpoint(endpoint))
    }
    self.type = type
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.description, forKey: .description)
    try container.encodeIfPresent(self.state, forKey: .state)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encodeIfPresent(self.deleteTime, forKey: .deleteTime)
    try container.encode(self.externalId, forKey: .externalId)
    try container.encodeIfPresent(self.lastConnectionTime, forKey: .lastConnectionTime)
    try container.encode(self.uniqueId, forKey: .uniqueId)
    try container.encodeIfPresent(self.authority, forKey: .authority)
    try container.encodeIfPresent(self.monitoringConfig, forKey: .monitoringConfig)

    if let choice = self.type {
      switch choice {
      case .endpoint(let value):
        try container.encode(value, forKey: .endpoint)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Type of resource represented by this Membership
  public enum TypeOneOf: Codable, Equatable, Sendable {
    /// Optional. Endpoint information to reach this member.
    indirect case endpoint(MembershipEndpoint)
  }

  /// The type URL for `Membership`: `"type.googleapis.com/google.cloud.gkehub.v1.Membership"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkehub.v1.Membership"
  }

  /// Initialize an instance of `Membership` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.gkehub.v1.Membership"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `Membership` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
