// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Namespace represents a namespace across the Fleet
public struct Namespace: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The resource name for the namespace
  /// `projects/{project}/locations/{location}/namespaces/{namespace}`
  public var name: Swift.String = Swift.String()

  /// Output only. Google-generated UUID for this resource. This is unique across
  /// all namespace resources. If a namespace resource is deleted and another
  /// resource with the same name is created, it gets a different uid.
  public var uid: Swift.String = Swift.String()

  /// Output only. When the namespace was created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. When the namespace was last updated.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. When the namespace was deleted.
  public var deleteTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. State of the namespace resource.
  public var state: NamespaceLifecycleState? = nil

  /// Required. Scope associated with the namespace
  public var scope: Swift.String = Swift.String()

  /// Optional. Namespace-level cluster namespace labels. These labels are
  /// applied to the related namespace of the member clusters bound to the parent
  /// Scope. Scope-level labels (`namespace_labels` in the Fleet Scope
  /// resource) take precedence over Namespace-level labels if they share
  /// a key. Keys and values must be Kubernetes-conformant.
  public var namespaceLabels: [Swift.String: Swift.String] = [:]

  /// Optional. Labels for this Namespace.
  public var labels: [Swift.String: Swift.String] = [:]

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Namespace`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Namespace().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let uid = CodingKeys(stringValue: "uid")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let deleteTime = CodingKeys(stringValue: "deleteTime")
    static let state = CodingKeys(stringValue: "state")
    static let scope = CodingKeys(stringValue: "scope")
    static let namespaceLabels = CodingKeys(stringValue: "namespaceLabels")
    static let labels = CodingKeys(stringValue: "labels")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "uid",
      "createTime",
      "updateTime",
      "deleteTime",
      "state",
      "scope",
      "namespaceLabels",
      "labels",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uid) {
      self.uid = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    self.deleteTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .deleteTime)
    self.state = try container.decodeIfPresent(NamespaceLifecycleState.self, forKey: .state)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .scope) {
      self.scope = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .namespaceLabels)
    {
      self.namespaceLabels = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.uid, forKey: .uid)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encodeIfPresent(self.deleteTime, forKey: .deleteTime)
    try container.encodeIfPresent(self.state, forKey: .state)
    try container.encode(self.scope, forKey: .scope)
    try container.encode(self.namespaceLabels, forKey: .namespaceLabels)
    try container.encode(self.labels, forKey: .labels)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkehub.v1.Namespace"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
