// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// ResourceOptions represent options for Kubernetes resource generation.
public struct ResourceOptions: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. The Connect agent version to use for connect_resources. Defaults
  /// to the latest GKE Connect version. The version must be a currently
  /// supported version, obsolete versions will be rejected.
  public var connectVersion: Swift.String = Swift.String()

  /// Optional. Use `apiextensions/v1beta1` instead of `apiextensions/v1` for
  /// CustomResourceDefinition resources.
  /// This option should be set for clusters with Kubernetes apiserver versions
  /// <1.16.
  public var v1Beta1Crd: Swift.Bool = Swift.Bool()

  /// Optional. Major and minor version of the Kubernetes cluster. This is only
  /// used to determine which version to use for the CustomResourceDefinition
  /// resources, `apiextensions/v1beta1` or`apiextensions/v1`.
  public var k8SVersion: Swift.String = Swift.String()

  /// Optional. Git version of the Kubernetes cluster. This is only used to gate
  /// the Connect Agent migration to svc.id.goog on GDC-SO 1.33.100 patch and
  /// above.
  public var k8SGitVersion: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ResourceOptions`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ResourceOptions().with { $0.connectVersion = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let connectVersion = CodingKeys(stringValue: "connectVersion")
    static let v1Beta1Crd = CodingKeys(stringValue: "v1beta1Crd")
    static let k8SVersion = CodingKeys(stringValue: "k8sVersion")
    static let k8SGitVersion = CodingKeys(stringValue: "k8sGitVersion")

    static let _knownKeys: Set<Swift.String> = [
      "connectVersion",
      "v1beta1Crd",
      "k8sVersion",
      "k8sGitVersion",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .connectVersion) {
      self.connectVersion = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .v1Beta1Crd) {
      self.v1Beta1Crd = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .k8SVersion) {
      self.k8SVersion = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .k8SGitVersion) {
      self.k8SGitVersion = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.connectVersion, forKey: .connectVersion)
    try container.encode(self.v1Beta1Crd, forKey: .v1Beta1Crd)
    try container.encode(self.k8SVersion, forKey: .k8SVersion)
    try container.encode(self.k8SGitVersion, forKey: .k8SGitVersion)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `ResourceOptions`: `"type.googleapis.com/google.cloud.gkehub.v1.ResourceOptions"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkehub.v1.ResourceOptions"
  }

  /// Initialize an instance of `ResourceOptions` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.gkehub.v1.ResourceOptions"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `ResourceOptions` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
