// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// SecurityPostureConfig defines the flags needed to enable/disable features for
/// the Security Posture API.
public struct SecurityPostureConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Sets which mode to use for Security Posture features.
  public var mode: SecurityPostureConfig.Mode = SecurityPostureConfig.Mode()

  /// Sets which mode to use for vulnerability scanning.
  public var vulnerabilityMode: SecurityPostureConfig.VulnerabilityMode =
    SecurityPostureConfig.VulnerabilityMode()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SecurityPostureConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SecurityPostureConfig().with { $0.mode = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let mode = CodingKeys(stringValue: "mode")
    static let vulnerabilityMode = CodingKeys(stringValue: "vulnerabilityMode")

    static let _knownKeys: Set<Swift.String> = [
      "mode",
      "vulnerabilityMode",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(SecurityPostureConfig.Mode.self, forKey: .mode) {
      self.mode = value
    }
    if let value = try container.decodeIfPresent(
      SecurityPostureConfig.VulnerabilityMode.self, forKey: .vulnerabilityMode)
    {
      self.vulnerabilityMode = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.mode, forKey: .mode)
    try container.encode(self.vulnerabilityMode, forKey: .vulnerabilityMode)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Mode defines enablement mode for GKE Security posture features.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Mode: Codable, Equatable, Hashable, Sendable {
    /// Default value not specified.
    case unspecified
    /// Disables Security Posture features on the cluster.
    case disabled
    /// Applies Security Posture features on the cluster.
    case basic
    /// Applies the Security Posture off cluster Enterprise level features.
    case enterprise
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .disabled: return 1
      case .basic: return 2
      case .enterprise: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "MODE_UNSPECIFIED"
      case .disabled: return "DISABLED"
      case .basic: return "BASIC"
      case .enterprise: return "ENTERPRISE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Mode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "MODE_UNSPECIFIED": self = .unspecified
      case "DISABLED": self = .disabled
      case "BASIC": self = .basic
      case "ENTERPRISE": self = .enterprise
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Mode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .disabled
      case 2: self = .basic
      case 3: self = .enterprise
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("MODE_UNSPECIFIED")
      case .disabled: return try container.encode("DISABLED")
      case .basic: return try container.encode("BASIC")
      case .enterprise: return try container.encode("ENTERPRISE")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// VulnerabilityMode defines enablement mode for vulnerability scanning.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum VulnerabilityMode: Codable, Equatable, Hashable, Sendable {
    /// Default value not specified.
    case unspecified
    /// Disables vulnerability scanning on the cluster.
    case vulnerabilityDisabled
    /// Applies basic vulnerability scanning on the cluster.
    case vulnerabilityBasic
    /// Applies the Security Posture's vulnerability on cluster Enterprise level
    /// features.
    case vulnerabilityEnterprise
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .vulnerabilityDisabled: return 1
      case .vulnerabilityBasic: return 2
      case .vulnerabilityEnterprise: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "VULNERABILITY_MODE_UNSPECIFIED"
      case .vulnerabilityDisabled: return "VULNERABILITY_DISABLED"
      case .vulnerabilityBasic: return "VULNERABILITY_BASIC"
      case .vulnerabilityEnterprise: return "VULNERABILITY_ENTERPRISE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:VulnerabilityMode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "VULNERABILITY_MODE_UNSPECIFIED": self = .unspecified
      case "VULNERABILITY_DISABLED": self = .vulnerabilityDisabled
      case "VULNERABILITY_BASIC": self = .vulnerabilityBasic
      case "VULNERABILITY_ENTERPRISE": self = .vulnerabilityEnterprise
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:VulnerabilityMode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .vulnerabilityDisabled
      case 2: self = .vulnerabilityBasic
      case 3: self = .vulnerabilityEnterprise
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("VULNERABILITY_MODE_UNSPECIFIED")
      case .vulnerabilityDisabled: return try container.encode("VULNERABILITY_DISABLED")
      case .vulnerabilityBasic: return try container.encode("VULNERABILITY_BASIC")
      case .vulnerabilityEnterprise: return try container.encode("VULNERABILITY_ENTERPRISE")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The type URL for `SecurityPostureConfig`: `"type.googleapis.com/google.cloud.gkehub.v1.SecurityPostureConfig"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkehub.v1.SecurityPostureConfig"
  }

  /// Initialize an instance of `SecurityPostureConfig` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.gkehub.v1.SecurityPostureConfig"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `SecurityPostureConfig` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
