// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request to update a fleet namespace.
public struct UpdateScopeNamespaceRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. A namespace with fields updated. The 'name' field in this
  /// namespace is used to identify the resource to update. Given 'updated'
  /// prefix to follow go/proto-best-practices-checkers#keyword_conflict
  public var scopeNamespace: Namespace? = nil

  /// Required. The fields to be updated.
  public var updateMask: GoogleWKT.WKTFieldMask? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `UpdateScopeNamespaceRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpdateScopeNamespaceRequest().with { $0.scopeNamespace = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let scopeNamespace = CodingKeys(stringValue: "scopeNamespace")
    static let updateMask = CodingKeys(stringValue: "updateMask")

    static let _knownKeys: Set<Swift.String> = [
      "scopeNamespace",
      "updateMask",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.scopeNamespace = try container.decodeIfPresent(Namespace.self, forKey: .scopeNamespace)
    self.updateMask = try container.decodeIfPresent(
      GoogleWKT.WKTFieldMask.self, forKey: .updateMask)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.scopeNamespace, forKey: .scopeNamespace)
    try container.encodeIfPresent(self.updateMask, forKey: .updateMask)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkehub.v1.UpdateScopeNamespaceRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
